# Config for https://github.com/toolmantim/release-drafter
name-template: '$NEXT_PATCH_VERSION'

change-template: '- $TITLE [#$NUMBER](https://github.com/akka/alpakka/issues/$NUMBER) by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  ## Changes

  $CHANGES
