pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge

  - name: Merge PRs that have been labeled
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#changes-requested-reviews-by=0"
      - label=merge-when-green
    actions:
      merge:
        method: merge
