name: ci

on:
  pull_request:
  push:
    branches: ['main']
    tags: ['[0-9]']

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.8, adopt@1.11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - uses: coursier/cache-action@v6
      - run: "sbt +test mimaReportBinaryIssues 'set sbtplugin/scriptedSbt := \"1.2.8\"' 'scripted sbt-mima-plugin/minimal'"
  testFunctional:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        scala: [2.11, 2.12, 2.13, 3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - uses: coursier/cache-action@v6
      - run: sbt "functional-tests/runMain com.typesafe.tools.mima.lib.UnitTests -${{ matrix.scala }}"
  testScripted:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        scripted: [1of2, 2of2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - uses: coursier/cache-action@v6
      - run: sbt "scripted sbt-mima-plugin/*${{ matrix.scripted }}"
  testIntegration:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - uses: coursier/cache-action@v6
      - run: sbt IntegrationTest/test
